feat: prevent a workflow from stopping when pre-commit fails (#197)
* feat: Prevent a workflow from stopping when pre-commit fails

Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>

* use pre-commit config

Co-authored-by: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>

* fix comments

Co-authored-by: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>

Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Co-authored-by: Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>

diff --git a/pre-commit/action.yaml b/pre-commit/action.yaml
--- a/pre-commit/action.yaml
+++ b/pre-commit/action.yaml
@@ -18,8 +18,22 @@ runs:
       with:
         go-version: ^1.16
 
+    - name: Install pre-commit
+      run: |
+        python -m pip install pre-commit
+      shell: bash
+
     - name: Run pre-commit
-      uses: pre-commit/action@v2.0.3
-      with:
-        extra_args: --all-files --config ${{ inputs.pre-commit-config }}
-        token: ${{ inputs.token }}
+      run: |
+        pre-commit run -a --config ${{ inputs.pre-commit-config }}
+      shell: bash
+
+    - name: Push pre-commit fixes
+      if: always() # Push changes even when pre-commit fails
+      run: |
+        if ! git diff --quiet; then
+          git add -u
+          git commit -m "pre-commit fixes"
+          git push
+        fi
+      shell: bash
