bug: fix errors such as following ones
  * Idempotency bugs
  * Version mismatch cannot be handled
  * Wrong/missing descriptions
  * ... etc

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

diff --git a/bump-new-version/action.yaml b/bump-new-version/action.yaml
--- a/bump-new-version/action.yaml
+++ b/bump-new-version/action.yaml
@@ -1,4 +1,5 @@
 name: bump package.xml version
+description: Bump version in all package.xml files
 
 inputs:
   github_token:
@@ -67,9 +68,8 @@ runs:
           git checkout -b ${{ steps.generate_branch_name.outputs.branch_name }} origin/${{ inputs.source_branch }}
         fi
 
-    # Generate changelog and do release
+    # Generate changelog
     - name: Generate changelog and do release
-      id: generate_release
       shell: bash
       run: |
         sudo apt-get update && sudo apt-get install -y python3-pip
@@ -79,32 +79,119 @@ runs:
         # As we have no way to avoid by command options, and 'no change' itself is not a problem, so we ignore the error.
         catkin_generate_changelog --all || true
 
+        # Check if there is any change
+        if [ -z "$(git status --porcelain)" ]; then
+          echo "No change to commit. Exiting..."
+          exit 0
+        fi
+
         # Add all files to git
         git add *
         git commit -m 'chore: update all "CHANGELOG.rst"s'
 
+    # Pre-check version mismatch between all the package.xml files:
+    # - If there is a mismatch, commit the changes
+    # - If there is no mismatch, do nothing
+    - name: Pre-check version mismatch
+      shell: bash
+      run: |
+        # List remote tags that match x.y.z
+        git fetch --tags
+        TAGS=$(git tag -l)
+      
+        # Find the latest tag
+        if [ -z "$TAGS" ]; then
+          echo "No tag found. Let's use 0.0.0 as the latest tag."
+          LATEST_TAG="0.0.0"
+        else
+          # Find the latest tag
+          TAGS=$(echo "$TAGS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)
+
+          # Check if there is/are tag(s) that matches the version
+          if [ -z "$TAGS" ]; then
+            echo "No pattern matched tag found. Let's use 0.0.0 as the latest tag."
+            LATEST_TAG="0.0.0"
+          else
+            echo "Existing tags:"
+            echo "$TAGS"
+
+            # Pick the newest tag
+            LATEST_TAG=$(echo "$TAGS" | tail -n1)
+          fi
+        fi
+
+        echo "Checking if the version has a valid format (x.y.z) and same as the latest tag"
+
+        while IFS= read -r file; do
+          CANDIDATE=$(grep '<version>' "$file" | head -1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
+          if [[ "$CANDIDATE" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            # If there is a mismatch, commit the changes
+            if [[ "$CANDIDATE" != "$LATEST_TAG" ]]; then
+              echo "$file has inconsistent version $CANDIDATE (expected $LATEST_TAG). Fixing to $LATEST_TAG..."
+              sed -i "s/<version>.*<\/version>/<version>$LATEST_TAG<\/version>/" "$file"
+            fi
+          else
+            echo "$file has invalid format version $CANDIDATE (expected x.y.z). Fixing to $LATEST_TAG..."
+            sed -i "s/<version>.*<\/version>/<version>$LATEST_TAG<\/version>/" "$file"
+          fi
+        done < <(find . -name package.xml)
+
+        # Check if there is any change
+        if [ -z "$(git status --porcelain)" ]; then
+          echo "No change to commit. Exiting..."
+          exit 0
+        fi
+
+        # Add all files to git
+        git add *
+        git commit -m 'fix: to be consistent version in all package.xml(s)'
+
+    # Bump version and push the branch
+    - name: Bump version and push the branch
+      id: bump_version_and_push_branch
+      shell: bash
+      run: |
         # Check if new packages are added
         catkin_prepare_release -y --no-push --bump ${{ inputs.bump_version }}
 
-        # Get the version string from one of the package.xml
-        NEW_VERSION=
+        # Commit and push changes
+        git push origin ${{ steps.generate_branch_name.outputs.branch_name }}
+
+        # Get updated version by catkin_prepare_release from one of the package.xml
+        UPDATED_VERSION=
         while IFS= read -r file; do
-          NEW_VERSION=$(grep '<version>' "$file" | head -1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
+          UPDATED_VERSION=$(grep '<version>' "$file" | head -1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
           # Check if the version has a valid format: x.y.z
-          if [[ "$NEW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            echo "✅ New version is: $NEW_VERSION"
+          if [[ "$UPDATED_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            echo "✅ Updated version is: $UPDATED_VERSION"
             break
           else
-            echo "❌ $file has invalid format version $NEW_VERSION (expected x.y.z)"
+            echo "❌ $file has invalid format version $UPDATED_VERSION (expected x.y.z)"
             exit 1
           fi
         done < <(find . -name package.xml)
 
-        # Output the new version
-        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
+        # Output the updated version
+        echo "updated_version=$UPDATED_VERSION" >> $GITHUB_OUTPUT
 
-        # Commit and push changes
-        git push origin ${{ steps.generate_branch_name.outputs.branch_name }}
+    - name: Ensure label exists
+      id: ensure_label_exists
+      shell: bash
+      env:
+        GITHUB_TOKEN: ${{ inputs.github_token }}
+      run: |
+        LABEL_NAME="release:bump-version"
+        LABEL_COLOR="f29513"    # orange
+        LABEL_DESCRIPTION="Label to trigger release workflow"
+        if ! gh label list | grep -wq "$LABEL_NAME"; then
+          echo "Label '$LABEL_NAME' does not exist, creating it..."
+          gh label create "$LABEL_NAME" --color "$LABEL_COLOR" --description "$LABEL_DESCRIPTION"
+        else
+          echo "Label '$LABEL_NAME' already exists."
+        fi
+
+        # Output the label name
+        echo "label_name=$LABEL_NAME" >> $GITHUB_OUTPUT
 
     - name: Create Pull Request using gh
       id: create_pr
@@ -112,11 +199,13 @@ runs:
       env:
         GITHUB_TOKEN: ${{ inputs.github_token }}
       run: |
+        # Create a PR: the label is used in the release workflow
         gh pr create \
           --base ${{ inputs.target_branch }} \
           --head ${{ steps.generate_branch_name.outputs.branch_name }} \
-          --title "chore: bump version (${{ steps.generate_release.outputs.new_version }}) and update changelog" \
-          --body "Bumped version (${{ steps.generate_release.outputs.new_version }}) in package.xml"
+          --title "chore: bump version (${{ steps.bump_version_and_push_branch.outputs.updated_version }}) and update changelog" \
+          --body "Bumped version (${{ steps.bump_version_and_push_branch.outputs.updated_version }}) in package.xml" \
+          --label ${{ steps.ensure_label_exists.outputs.label_name }}
 
         if [ $? -ne 0 ]; then
           echo "pr_created=true" >> $GITHUB_OUTPUT
@@ -124,7 +213,7 @@ runs:
           echo "pr_created=false" >> $GITHUB_OUTPUT
         fi
 
-    # Delete the remote branch if the PR creation failed
+    # (Idempotent) Delete the remote branch if the PR creation failed
     - name: Delete the remote branch if the PR creation failed
       if: steps.create_pr.outputs.pr_created == false
       shell: bash
